# Generated by Django 4.1.3 on 2022-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subcategory_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(null=True, to='api.subcategory'),
        ),
    ]
