# Generated by Django 4.1.3 on 2022-11-27 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 11, 27)),
        ),
    ]
