# Generated by Django 4.1.3 on 2023-02-21 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
    ]
