# Generated by Django 4.1.3 on 2023-02-23 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 2, 23)),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
