# Generated by Django 4.1.3 on 2023-02-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminuser_alter_article_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
