# Generated by Django 4.1.3 on 2023-02-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
