# Generated by Django 4.1.3 on 2023-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_is_admin_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
