# Generated by Django 4.1.3 on 2023-02-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_alter_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='User',
        ),
    ]
