# Generated by Django 4.1.3 on 2023-02-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0011_rename_useraccount_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
